library("dplyr")
library("readr")
library("stringr")

# this file should contain functions to extract the data and generate training,
# validation and test sets

# This function returns a single data frame with data and events combined for all subjects and series.
# example usage:
# library("ggplot2")
# t <- get_datasets(1, 1:8)
# ggplot(t, aes(x = series_seq_id, y = F7)) + facet_wrap(~ series) + geom_line()
get_datasets <- function(subjects = 1:12, series = 1:8, base_path = "../Data/train", verbose=FALSE) {
  construct_filename <- function(subject, series_id, type) {
    paste0(base_path, "/subj", subject, "_series", series_id, "_", type, ".csv")
  }

  # could be done in parallel
  expand.grid(subject = subjects, series = series) %>%
    apply(1, function(row) {
      if (verbose) cat("Reading the combination: ",row[1]," (subj) ", row[2], "(series).\n")
      data <- read_csv(construct_filename(row[["subject"]], row[["series"]], "data"),progress=FALSE)
      if (file.exists(construct_filename(row[["subject"]], row[["series"]], "events"))) {
        events <- read_csv(construct_filename(row[["subject"]], row[["series"]], "events"),progress=FALSE)
        data %>% left_join(events, by = "id")
      }
      data
    }) %>%
    bind_rows %>%
    mutate(subject = str_match(id, "subj([[:digit:]]{1,2})")[, 2],
           series = str_match(id, "series([[:digit:]])_")[, 2],
           series_seq_id = str_match(id, "_([[:digit:]]+)")[, 2]) %>%
    mutate(subject = factor(subject),
           series = as.numeric(series),
           series_seq_id = as.numeric(series_seq_id))
}

# this function splits the data frame generated by get_datasets in a
# training and validation set
# It currently only splits complete series
# Next step could be that it makes splits within series as well
# example usage:
# d <- generate_validation_training_set(get_datasets(1, 1:8)) %>%
#       filter(is_part_of_training_set)
generate_validation_training_set <- function(base_data, training_set_size = 0.7) {
  training_set_indicator <- expand.grid(subject = unique(base_data$subject),
                                        series = unique(base_data$series)) %>%
  mutate(is_part_of_training_set = runif(nrow(.)) <= training_set_size)
  base_data %>%
    left_join(training_set_indicator, by = c("subject", "series"))
}
