library("dplyr")
library("readr")
library("stringr")

# this file should contain functions to extract the data and generate training,
# validation and test sets

# This function returns a single data frame with data and events combined for all subjects and series.
# example usage:
# library("ggplot2")
# t <- get_datasets(1, 1:8)
# ggplot(t, aes(x = series_seq_id, y = F7)) + facet_wrap(~ series) + geom_line()
get_datasets <- function(subjects = 1:12, series = 1:8, base_path = "../Data/train", verbose=FALSE) {
  construct_filename <- function(subject, series_id, type) {
    paste0(base_path, "/subj", subject, "_series", series_id, "_", type, ".csv")
  }

  # could be done in parallel
  expand.grid(subject = subjects, series = series) %>%
    apply(1, function(row) {
      if (verbose) cat("Reading the combination: ",row[1]," (subj) ", row[2], "(series).\n")
      data <- read_csv(construct_filename(row[["subject"]], row[["series"]], "data"),progress=FALSE)
      if (file.exists(construct_filename(row[["subject"]], row[["series"]], "events"))) {
        events <- read_csv(construct_filename(row[["subject"]], row[["series"]], "events"),progress=FALSE)
        return(data %>% left_join(events, by = "id"))
      } else {
        return(data)
      }
    }) %>%
    bind_rows %>%
    mutate(subject = str_match(id, "subj([[:digit:]]{1,2})")[, 2],
           series = str_match(id, "series([[:digit:]])_")[, 2],
           series_seq_id = str_match(id, "_([[:digit:]]+)")[, 2]) %>%
    mutate(subject = factor(subject),
           series = as.numeric(series),
           series_seq_id = as.numeric(series_seq_id))
}

# this function splits the data frame generated by get_datasets in a
# training and validation set
# It currently only splits complete series
# Next step could be that it makes splits within series as well
# example usage:
# d <- generate_validation_training_set(get_datasets(1, 1:8)) %>%
#       filter(is_part_of_training_set)
generate_validation_training_set <- function(base_data, training_set_size = 0.7) {
  training_set_indicator <- expand.grid(subject = unique(base_data$subject),
                                        series = unique(base_data$series)) %>%
  mutate(is_part_of_training_set = runif(nrow(.)) <= training_set_size)
  base_data %>%
    left_join(training_set_indicator, by = c("subject", "series"))
}


######################################################################
### Action start for reading the data
######################################################################

##Load the training data (hoehle: full dataset crashes R on my computer :-()
eegTrain <- get_datasets(subjects=1:12, series = 1:3, verbose=TRUE)
##Load the competition test data.
eegTest <- get_datasets(subjects = 1:12, series = 9:10, base_path = "../Data/test", verbose=TRUE)

##Add column illustrating if in validation dataset or not.
eegTrain <- generate_validation_training_set(eegTrain)
dim(eegTrain)

##Define Event types
theEventTypes <- c("HandStart","FirstDigitTouch","BothStartLoadPhase","LiftOff","Replace","BothReleased")

##Make a factor containing the response
whichEvent <- apply(eegTrain[, theEventTypes], 1, which.max)
eegTrain$Event <- factor(theEventTypes[whichEvent], levels=theEventTypes)

##Data needs to be reduced (say 10%) to enable possibility to test code. Remove later
eegTrain$is_part_of_reduced_set <- (runif(nrow(eegTrain)) < 0.1)

##No need for this, but we do it to reduce size of data set.
train <- subset(eegTrain, ( is_part_of_training_set) & is_part_of_reduced_set)
test  <- subset(eegTrain, (!is_part_of_training_set) & is_part_of_reduced_set)

##Features
features <- c("Fp1","Fp2","F7","F3","Fz","F4","F8","FC5","FC1","FC2","FC6","T7","C3","Cz","C4","T8","TP9","CP5","CP1","CP2","CP6","TP10","P7","P3","Pz","P4","P8","PO9","O1","Oz","O2","PO10")

##Standardize features according to mean and sd in training data.
meanFeatureTrain <- apply(train[,features],2,mean)
sdFeatureTrain   <-  apply(train[,features],2,sd)

# we need to be careful here. This leaks information about the future.
# you can only use the information from other series or the data points that have already be gathered
for (f in features) {
  train[,f] <- (train[,f] - meanFeatureTrain[f])/sdFeatureTrain[f]
  test[,f] <- (test[,f] - meanFeatureTrain[f])/sdFeatureTrain[f]
  eegTest[,f] <- (eegTest[,f] - meanFeatureTrain[f])/sdFeatureTrain[f]
}

